### ISSUE TITLE
Multi-directory sites throw error

### ISSUE THREAD

**Issue by Truffula** [jashkenas/docco#309]
I've just been looking at #303, and noticed that c52298c167cdebacf5a2cc563db2dd6a69b52d3f introduced a breaking change such that multi-directory sites can't generate any more. It probably wasn't picked up earlier because the version number wasn't changed - I suspect I may have previously been running on the npm version which was not in sync with github.

```
$ docco app/**/*.md
docco: app/adapters/application.coffee.md -> docs/app/adapters/application.coffee.md.html

fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'docs/app/adapters/application.coffee.md.html'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.writeFileSync (fs.js:966:15)
    at write (/Users/Truffula/Development/Projects/docco/docco.js:154:15)
    at /Users/Truffula/Development/Projects/docco/docco.js:45:11
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)
```

I'm working on a fix which may tie in to #303.

**Comment by thomasklein** [comment]
Hi guys! Any news on this one?
