### ISSUE TITLE
Docco breaks (issues with dependencies)

### ISSUE THREAD

**Issue by papakai** [jashkenas/docco#417]
Hi @jashkenas 

I am faced with the following problem:

```
> npx docco -l parallel -o docs/docco src/*.ts

Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277
/...homefolder.../git/node-sdk/node_modules/docco/docco.js:214
      results.push(section.docsHtml = marked(section.docsText));
                                      ^

TypeError: marked is not a function
    at format (/...homefolder.../git/node-sdk/node_modules/docco/docco.js:214:39)
    at /...homefolder.../git/node-sdk/node_modules/docco/docco.js:124:11
    at /...homefolder.../git/node-sdk/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

**Comment by georgealways** [comment]
Hey -- same issue over here.

**Comment by jashkenas** [comment]
Thanks for letting me know!

I've just pushed a new version to npm — `docco 0.9.1` — that should sort this out for you. Let me know if you have any problems.

**Comment by papakai** [comment]
@jashkenas thanks so much, worked like a charm!
